### ISSUE TITLE
Features variable is rotationally invariant

### ISSUE THREAD

**Issue by alejandrovr** [qq456cvb/PRIN#5]
Dear PRIN developers,

Again, thanks for this amazing repo. I have a small question, should the features variable in model.py: `return features, prediction` be rotationally invariant? That is, should the same point cloud always return the same features vector in any possible orientation?

Best regards,
Alejandro

**Comment by qq456cvb** [comment]
Yes, it is, but up to a discretization error, because we are only able to work with 3D spherical voxel convolution up to a grid with limited resolition (say 32^3). Any rotation that does not lie on the grid points (1/32, 2/32, etc.) will induce a small error due to interpolation.

**Comment by alejandrovr** [comment]
I see... that's great! Thanks for the reply :)
