### ISSUE TITLE
How can I sampling package in 'dataset.py'?

### ISSUE THREAD

**Issue by ThreeWaterGG** [qq456cvb/PRIN#7]

**Comment by ThreeWaterGG** [comment]
> ModuleNotFoundError: No module named 'sampling'
> How can I get 'sampling' package in 'dataset.py'?

**Comment by tokudai-vs** [comment]
I have the same problem. Can you share how you solved this issue?

**Comment by ThreeWaterGG** [comment]
> 
> 
> I have the same problem. Can you share how you solved this issue?

Just compile the script under src.
